#!/usr/bin/env node
/**
 * seed-patches.js
 * Auto-fetches bundle release patches from the Valorant wiki and writes
 * public/data/bundle-patches.json.
 *
 * Run from sandbox/astro/:
 *   node scripts/seed-patches.js
 *
 * Strategy per bundle:
 *   1. "{name} Collection"
 *   2. "{name} Capsule"          (fallback — some bundles use this naming)
 *   3. "{name}"                  (direct page — e.g. Arcane Collector's Set)
 *   where {name} = bundleName with "//" → " " and spaces normalized.
 *
 * Keeps existing values as fallback when the wiki has no data for a bundle.
 */

import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dir = dirname(fileURLToPath(import.meta.url));
const SKINS_DB  = join(__dir, '..', 'public', 'data', 'skins-db.json');
const PATCHES   = join(__dir, '..', 'public', 'data', 'bundle-patches.json');
const WIKI_API  = 'https://valorant.fandom.com/api.php';
const UA        = 'Valorandle-patch-seed/2.0 (hobby project, no commercial use)';
const DELAY_MS  = 250; // be polite to the wiki

// ── Helpers ───────────────────────────────────────────────────────────────────

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

/** Normalize a bundle name for use as a MediaWiki page title component. */
function normalizeTitle(name) {
  return name
    .replace(/\/\//g, ' ')   // "Prime//2.0" → "Prime 2.0"
    .replace(/\s+/g, ' ')    // collapse multiple spaces
    .trim();
}

/** Fetch wikitext for a page title. Returns '' if missing or on error. */
async function fetchWikitext(title) {
  const url = new URL(WIKI_API);
  url.searchParams.set('action',      'query');
  url.searchParams.set('titles',      title);
  url.searchParams.set('prop',        'revisions');
  url.searchParams.set('rvprop',      'content');
  url.searchParams.set('rvslots',     'main');
  url.searchParams.set('format',      'json');
  url.searchParams.set('formatversion', '2');

  try {
    const res = await fetch(url.toString(), {
      headers: { 'User-Agent': UA },
      signal: AbortSignal.timeout(10_000),
    });
    if (!res.ok) return '';
    const data = await res.json();
    const page = data.query?.pages?.[0];
    if (!page || page.missing) return '';
    return page.revisions?.[0]?.slots?.main?.content ?? '';
  } catch {
    return '';
  }
}

/** Extract the first {{patch|X.YY}} from wikitext. Returns null if not found. */
function extractPatch(wikitext) {
  const m = wikitext.match(/\{\{patch\|([0-9]+\.[0-9]+)/i);
  return m ? m[1] : null;
}

/** Try several page title variants and return the first patch found. */
async function resolvePatch(bundleName) {
  const base = normalizeTitle(bundleName);
  const candidates = [
    `${base} Collection`,
    `${base} Capsule`,
    base,
  ];
  for (const title of candidates) {
    const wikitext = await fetchWikitext(title);
    if (!wikitext) continue;
    const patch = extractPatch(wikitext);
    if (patch) return { patch, title };
  }
  return null;
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  // Load bundle list from skins-db
  if (!existsSync(SKINS_DB)) {
    console.error('skins-db.json not found. Run seed-skins.js first.');
    process.exit(1);
  }
  const { bundles } = JSON.parse(readFileSync(SKINS_DB, 'utf-8'));

  // Load existing patches (keep manual overrides and the _note key)
  const existing = existsSync(PATCHES)
    ? JSON.parse(readFileSync(PATCHES, 'utf-8'))
    : {};

  console.log(`Looking up ${bundles.length} bundles on the Valorant wiki…\n`);

  const result = { _note: existing._note ?? 'Auto-generated by seed-patches.js. Edit manually to override.' };
  let found = 0, kept = 0, missing = 0;
  const missingList = [];

  for (const bundle of bundles) {
    process.stdout.write(`  ${bundle} … `);

    const resolved = await resolvePatch(bundle);
    await sleep(DELAY_MS);

    if (resolved) {
      result[bundle] = resolved.patch;
      console.log(`${resolved.patch}  (via "${resolved.title}")`);
      found++;
    } else if (existing[bundle] !== undefined) {
      // Keep existing value (could be a manually set patch or null)
      result[bundle] = existing[bundle];
      console.log(existing[bundle] !== null ? `${existing[bundle]}  (kept existing)` : 'null  (kept existing)');
      kept++;
    } else {
      result[bundle] = null;
      console.log('null  (not found)');
      missing++;
      missingList.push(bundle);
    }
  }

  mkdirSync(dirname(PATCHES), { recursive: true });
  writeFileSync(PATCHES, JSON.stringify(result, null, 2), 'utf-8');

  console.log(`\n✓ Done.`);
  console.log(`  Wiki:    ${found} bundles resolved automatically`);
  console.log(`  Kept:    ${kept} values from existing bundle-patches.json`);
  console.log(`  Missing: ${missing} bundles (set to null, excluded from daily pool)`);
  if (missingList.length) {
    console.log(`\n  Still null: ${missingList.join(', ')}`);
  }
}

main().catch(err => { console.error(err); process.exit(1); });
